project:
  type: website
  output-dir: ../docs

website:
  title: "CNS 2023: Simulation of spiking and BOLD signals using the ANNarchy simulator"

  page-navigation: true

  navbar:
    background: black
    logo: img/logowhite.png
    pinned: false

    right:
      - icon: github
        href: https://github.com/ANNarchy/CNS2023
        aria-label: GitHub

  sidebar:
    style: "docked"
    logo: img/qrcode.png

    contents:
      - text: annarchy.github.io/CNS2023
        file: index.qmd
      - section: "**Tutorial**"
        contents:
        - 1-Rationale.qmd
        - 2-ANNarchy.qmd
        - 3-Neurons.qmd
        - 4-Networks.qmd
        - 5-Plasticity.qmd
        - 6-Additional.qmd
        - 7-BOLD.qmd
      - section: "**Notebooks**"
        contents:
        - notebooks/RateCoded.ipynb
        - notebooks/AdEx.ipynb
        - notebooks/SynapticTransmission.ipynb
        - notebooks/COBA.ipynb
        - notebooks/STP.ipynb
        - notebooks/STDP.ipynb

  page-footer:
    center: |
      <https://annarchy.github.io/CNS2023>

format:
  html:
    theme: [sandstone, ../assets/webpage.scss]
    toc: false
    page-layout: full
    smooth-scroll: true
    html-math-method: katex

bibliography: references.bib
csl: ../assets/frontiers.csl

highlight-style: github
code-line-numbers: false

filters:
  - ../assets/center_images.lua
  - quarto

